# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 11:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('c_date', models.DateTimeField(default=datetime.datetime(2016, 7, 11, 17, 25, 19, 147000))),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=1000)),
                ('cm_date', models.DateTimeField(default=datetime.datetime(2016, 7, 11, 17, 25, 19, 148000))),
                ('owner', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('status', models.TextField()),
                ('image', models.ImageField(default='/postbox/images/1.jpg', null=True, upload_to='C:/Users/Jyothsna Boyina/PycharmProjects/post/postbox/static/postbox/')),
                ('p_date', models.DateTimeField(default=datetime.datetime(2016, 7, 11, 17, 25, 19, 148000))),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postbox.Categories')),
                ('owner', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postbox.Posts'),
        ),
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together=set([('owner', 'category')]),
        ),
    ]
