# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0002_auto_20160713_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='', null=True, upload_to=b''),
        ),
    ]
